// <auto-generated />
using APIOgVueAvslutning.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIOgVueAvslutning.Migrations
{
    [DbContext(typeof(CoockiesDBContext))]
    partial class CoockiesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("APIOgVueAvslutning.Models.Coockies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coockies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cookie with chocolate bites ",
                            Name = "Chocolate Cookie"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu quam pretium, maximus ligula non, lobortis elit. Nulla tristique facilisis erat, vel accumsan velit. Proin maximus tortor non nulla egestas, ac iaculis quam malesuada. Phasellus at volutpat diam. Aliquam vulputate a est ac posuere. Integer dignissim arcu vitae eros faucibus, sed iaculis tortor cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos",
                            Name = "Blueberry Cookie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu quam pretium, maximus ligula non, lobortis elit. Nulla tristique facilisis erat, vel accumsan velit. Proin maximus tortor non nulla egestas, ac iaculis quam malesuada. Phasellus at volutpat diam. Aliquam vulputate a est ac posuere. Integer dignissim arcu vitae eros faucibus, sed iaculis tortor cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos",
                            Name = "Apple Cookie"
                        });
                });

            modelBuilder.Entity("APIOgVueAvslutning.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blueberry"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Milk"
                        });
                });

            modelBuilder.Entity("CoockiesIngredients", b =>
                {
                    b.Property<int>("CoockiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoockiesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("CoockiesIngredients");

                    b.HasData(
                        new
                        {
                            CoockiesId = 1,
                            IngredientsId = 1
                        },
                        new
                        {
                            CoockiesId = 1,
                            IngredientsId = 2
                        },
                        new
                        {
                            CoockiesId = 1,
                            IngredientsId = 4
                        },
                        new
                        {
                            CoockiesId = 1,
                            IngredientsId = 5
                        },
                        new
                        {
                            CoockiesId = 1,
                            IngredientsId = 7
                        },
                        new
                        {
                            CoockiesId = 2,
                            IngredientsId = 2
                        },
                        new
                        {
                            CoockiesId = 2,
                            IngredientsId = 4
                        },
                        new
                        {
                            CoockiesId = 2,
                            IngredientsId = 5
                        },
                        new
                        {
                            CoockiesId = 2,
                            IngredientsId = 6
                        },
                        new
                        {
                            CoockiesId = 2,
                            IngredientsId = 7
                        },
                        new
                        {
                            CoockiesId = 3,
                            IngredientsId = 2
                        },
                        new
                        {
                            CoockiesId = 3,
                            IngredientsId = 3
                        },
                        new
                        {
                            CoockiesId = 3,
                            IngredientsId = 4
                        },
                        new
                        {
                            CoockiesId = 3,
                            IngredientsId = 5
                        },
                        new
                        {
                            CoockiesId = 3,
                            IngredientsId = 7
                        });
                });

            modelBuilder.Entity("CoockiesIngredients", b =>
                {
                    b.HasOne("APIOgVueAvslutning.Models.Coockies", null)
                        .WithMany()
                        .HasForeignKey("CoockiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIOgVueAvslutning.Models.Ingredients", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
